### ISSUE TITLE
what‘s the hardware of the project?

### ISSUE THREAD

**Issue by heimao0130** [kit-cel/gr-lte#1]
hello! nice to talk to you ! what's the hardware of the project ?and does the GNURadio only can  use the 3.7.0 or version above 3.7.0   are all  included ？ i install the 3.7.4 version  but the GRC files  are invalid?maybe it's the problem with the  version?can you give me help ?thank you！

**Comment by Keskebeu** [comment]
I am trying to compile this in linux mint and i am not succesful. Gnuradio 3.7.9? Any ideas?
