### ISSUE TITLE
hier_block_install_helper.grc missing

### ISSUE THREAD

**Issue by MountainLogic** [kit-cel/gr-lte#20]
examples/hier_block_install_helper.py is present, but examples/hier_block_install_helper.grc is missing in git

**Comment by skoslowski** [comment]
This is a regular python script. 
Nothing generated from GRC.

**Comment by MountainLogic** [comment]
Perhaps the documentation in Readme.md is incorrect regarding hier_block_install_helper.grc:

> compile hierarchical GRC blocks
These blocks are located in the 'examples' directory.
hierarchical GRC blocks must be generated by opening them in GRC and clicking Generate. Afterwards reload blocks or restart GRC. This makes the hier blocks available in GRC just as all the other blocks.
An alternative is to use the python script **examples/hier_block_install_helper.grc**, which calls 'grcc' for all grc files in the current directory and installs them.

**Comment by skoslowski** [comment]
Good catch. Thanks. 
Fixed in https://github.com/kit-cel/gr-lte/commit/7288cc3a50b528955bf45d4a1526eac416361014
